# Generated by Django 3.1.5 on 2021-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
